// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.36
// Please do not change anything in this file.
package class

import (
	"github.com/huoyijie/GoalGenerator/model"
)

type Student struct {
	model.Base
	Name     string    `binding:"required" goal:"<text>globalSearch,filter"`
	Teachers []Teacher `gorm:"many2many:student_teachers" binding:"required" goal:"<multiSelect>many2Many=class.Teacher.Name"`
}

func (*Student) Icon() string {
	return "student"
}

func (*Student) TranslatePkg() map[string]string {
	t := map[string]string{}
	t["en"] = "Class"
	t["zh-CN"] = "班级"
	return t
}

func (*Student) TranslateName() map[string]string {
	t := map[string]string{}
	t["en"] = "Student | students"
	t["zh-CN"] = "学生"
	return t
}

func (*Student) TranslateFields() map[string]map[string]string {
	return map[string]map[string]string{
		"en": {
			"ID":       "ID",
			"Name":     "Name",
			"Teachers": "Teachers",
		},
		"zh-CN": {
			"ID":       "ID",
			"Name":     "姓名",
			"Teachers": "老师",
		},
	}
}

func (m *Student) TranslateOptions() map[string]map[string]map[string]string {
	t := map[string]map[string]map[string]string{"en": {}, "zh-CN": {}}

	return t
}
