// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.15
// Please do not change anything in this file.
package auth

import (
    "github.com/huoyijie/GoalGenerator"
)

type Role struct { 
    goalgenerator.Base

    Name string `gorm:"unique" binding:"required,alphanum,min=3,max=40" goal:"<text>unique,sortable,globalSearch"`
}
