// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.9
// Please do not change anything in this file.
package auth

import (
    "time"
)

type Session struct { 

    ID uint `gorm:"primaryKey" goal:"<number>primary,uint,hidden"`
    Key string `gorm:"unique" binding:"required,alphanum,len=32" goal:"<uuid>unique,readonly,globalSearch"`
    UserID uint `goal:"<number>uint,autowired"`
    User User `binding:"required" goal:"<dropdown>belongTo=auth.User.Username,postonly,filter,globalSearch"`
    ExpireDate time.Time `gorm:"index" binding:"required" goal:"<calendar>showTime,showIcon,sortable,desc"`
}
