// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.16
// Please do not change anything in this file.
package auth

import (
    "github.com/huoyijie/GoalGenerator"
)

type User struct { 
    goalgenerator.Base

    Username string `gorm:"unique" binding:"required,alphanum,min=3,max=40" goal:"<text>unique,sortable,globalSearch,filter"`
    Email string `gorm:"unique" binding:"required,email" goal:"<text>unique,sortable,filter"`
    Password string `binding:"required,min=8" goal:"<password>secret,hidden"`
    IsSuperuser bool `goal:"<switch>readonly,filter"`
    IsActive bool `goal:"<switch>filter"`
}

func (*User) Lazy() {}
var _ goalgenerator.Lazy = (*User)(nil)
