// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.17
// Please do not change anything in this file.
package auth

import (
    "github.com/huoyijie/GoalGenerator/model"
)

type User struct { 
    model.Base

    Username string `gorm:"unique" binding:"required,alphanum,min=3,max=40" goal:"<text>unique,sortable,globalSearch,filter"`
    Email string `gorm:"unique" binding:"required,email" goal:"<text>unique,sortable,filter"`
    Password string `binding:"required,min=8" goal:"<password>hidden,secret"`
    IsSuperuser bool `goal:"<switch>readonly,filter"`
    IsActive bool `goal:"<switch>filter"`
}


func (*User) Lazy() {}
var _ model.Lazy = (*User)(nil)
