// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.9
// Please do not change anything in this file.
package auth

type User struct { 

    ID uint `gorm:"primaryKey" goal:"<number>primary,uint,sortable,asc"`
    Username string `gorm:"unique" binding:"required,alphanum,min=3,max=40" goal:"<text>unique,sortable,globalSearch"`
    Email string `gorm:"unique" binding:"required,email" goal:"<text>unique,sortable,globalSearch"`
    Password string `binding:"required,min=8" goal:"<password>secret,hidden"`
    IsSuperuser bool `goal:"<switch>readonly"`
    IsActive bool `goal:"<switch>"`
    Creator uint `gorm:"index" goal:"<number>uint,autowired"`
}
