// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.9
// Please do not change anything in this file.
package admin

import (
    "github.com/huoyijie/goal/auth"
    "time"
)

type OperationLog struct { 

    ID uint `gorm:"primaryKey" goal:"<number>primary,uint,hidden"`
    UserID uint `gorm:"index" goal:"<number>uint,hidden"`
    User auth.User `goal:"<dropdown>belongTo=auth.User.Username,sortable,globalSearch"`
    Date time.Time `gorm:"index" goal:"<calendar>showTime,sortable,desc"`
    IP string `goal:"<text>"`
    Group string `goal:"<text>hidden"`
    Item string `goal:"<text>hidden"`
    Action string `goal:"<text>"`
    ObjectID uint `goal:"<number>uint"`
}
