// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.17
// Please do not change anything in this file.
package admin

import (
    "github.com/huoyijie/GoalGenerator/model"
    "github.com/huoyijie/Goal/auth"
    "time"
)

type OperationLog struct { 
    model.Base

    UserID uint `gorm:"index" goal:"<number>hidden,uint"`
    User auth.User `goal:"<dropdown>sortable,globalSearch,filter,belongTo=auth.User.Username"`
    Date time.Time `gorm:"index" goal:"<calendar>sortable,desc,filter,showTime"`
    IP string `goal:"<text>filter"`
    Group string `goal:"<text>filter"`
    Item string `goal:"<text>filter"`
    Action string `goal:"<text>filter"`
    ObjectID uint `goal:"<number>uint"`
}


func (*OperationLog) Lazy() {}
var _ model.Lazy = (*OperationLog)(nil)
