// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.20
// Please do not change anything in this file.
package admin

import (
    "github.com/huoyijie/GoalGenerator/model"
    "github.com/huoyijie/Goal/auth"
    "time"
)

type OperationLog struct {

    model.Base

    UserID uint `gorm:"index" goal:"<number>hidden,uint"`
    User auth.User `goal:"<dropdown>sortable,globalSearch,filter,belongTo=auth.User.Username"`
    Date time.Time `gorm:"index" goal:"<calendar>sortable,desc,filter,showTime"`
    IP string `goal:"<text>filter"`
    Group string `goal:"<dropdown>filter,dynamicStrings"`
    Item string `goal:"<dropdown>filter,dynamicStrings"`
    Action string `goal:"<dropdown>filter,strings"`
    ObjectID uint `goal:"<number>uint"`
}
func (OperationLog) TableName() string {
    return "admin_operation_logs"
}
// Please implements this method in another file
// func (*OperationLog) GroupDynamicStrings() []string {
//     return []string{"some", "custom", "strings"}
// }
// Please implements this method in another file
// func (*OperationLog) ItemDynamicStrings() []string {
//     return []string{"some", "custom", "strings"}
// }
func (*OperationLog) ActionStrings() []string {
    return []string{"post", "put", "delete"}
}

func (*OperationLog) Icon() string {
    return "save"
}
func (*OperationLog) Lazy() {}

func (*OperationLog) Ctrl() {}
