// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.9
// Please do not change anything in this file.
package cdn

type Resource struct { 

    ID uint `gorm:"primaryKey" goal:"<number>primary,uint,sortable,desc"`
    File string `gorm:"unique" binding:"required" goal:"<file>unique,uploadTo=uploads,postonly,globalSearch"`
    Creator uint `gorm:"index" goal:"<number>uint,autowired"`
}
