// auto generated by https://github.com/huoyijie/GoalGenerator/releases/tag/v0.0.16
// Please do not change anything in this file.
package cdn

import (
    "github.com/huoyijie/GoalGenerator"
)

type Resource struct { 
    goalgenerator.Base

    File string `gorm:"unique" binding:"required" goal:"<file>unique,uploadTo=uploads,globalSearch,postonly,filter"`
}

func (*Resource) Lazy() {}
var _ goalgenerator.Lazy = (*Resource)(nil)
